<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>StaffAutomation.Reports</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StaffAutomation.Core\StaffAutomation.Core.vbproj" />
  </ItemGroup>

</Project>
